### ISSUE TITLE
symbols past row 9 won't work, columns past 9 are 1 off

### ISSUE THREAD

**Issue by FoxGaal** [inkiralet/libglyph-mcbe#1]
if you click E1 x:10 y:0 instead of giving you E1A0 Its E1100
example image:
![glyph_E1](https://github.com/inkiralet/libglyph-mcbe/assets/89459446/f8d26b53-24ce-4946-b32c-fbacdef202a6)

**Comment by FoxGaal** [comment]
this is the same same texture For E1 glyphs on the hive so if you paste the character in the chat you can test to see if it works

**Comment by inkiralet** [comment]
it really was a simple mistake.
I made a small correction and everything seems to be working now.
